title: ویکی کارِج
description: ویکی اطلاعات مهاجرت کاری حوزه توسعه نرم‌افزار
theme: just-the-docs

url: https://wiki.karej.ir

footer_content: "با ❤️ تقدیم به توسعه‌دهندگان فارسی‌زبان. کاری از <a href=\"https://hamed.blog\">حامد</a>"
